medallion_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/home/nilay/examen_ing_de_sw_n_data_final/warehouse/medallion.duckdb') }}"
      threads: 4
      extensions: ["parquet"]
